global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'rest-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['rest-api:8080']

  - job_name: 'soap-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['soap-api:8081']

  - job_name: 'graphql-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['graphql-api:4000']

  - job_name: 'grpc-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['grpc-api:8082']
